import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

type Props = Readonly<{
  children: React.ReactNode;
}>;

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'udemy-nextjs-fullstack',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="bg-red-300 p-4">
          <h1 className="text-2xl font-black">メインレイアウト</h1>
          <ul className="flex justify-start items-center gap-3 mt-2">
            <li className="hover:text-blue-500 font-semibold transition-all duration-300">
              <Link href="/">home</Link>
            </li>
            <li className="hover:text-blue-500 font-semibold transition-all duration-300">
              <Link href="/task">task</Link>
            </li>
            <li className="hover:text-blue-500 font-semibold transition-all duration-300">
              <Link href="/task/edit">edit</Link>
            </li>
            <li className="hover:text-blue-500 font-semibold transition-all duration-300">
              <Link href="/task/edit/1">1</Link>
            </li>
            <li className="hover:text-blue-500 font-semibold transition-all duration-300">
              <Link href="/task/edit/2">2</Link>
            </li>
          </ul>
          <ul className="flex justify-start items-center gap-3">
            <li className="hover:text-green-500 font-semibold transition-all duration-300">
              <Link href="/dashboard">dashboard</Link>
            </li>
          </ul>
          <ul className="flex justify-start items-center gap-3">
            <li className="hover:text-gray-500 font-semibold transition-all duration-300">
              <Link href="/sc">server component</Link>
            </li>
            <li className="hover:text-gray-500 font-semibold transition-all duration-300">
              <Link href="/cc">client component</Link>
            </li>
            <li className="hover:text-gray-500 font-semibold transition-all duration-300">
              <Link href="/sa">server action</Link>
            </li>
            <li className="hover:text-gray-500 font-semibold transition-all duration-300">
              <Link href="/api/tasks">route handlers</Link>
            </li>
          </ul>
        </header>
        {children}
      </body>
    </html>
  );
}
